name: CI Demo

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: Redhat-latest

    steps:
      - name: checkout Code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "CI/CD is working!"
